### PR TITLE
LaTeX output support

### PR DESCRIPTION
**Pull request by GarkGarcia**
A follow up of #16. There are a feel issues that I haven't resolved yet:

1. I tried using as few LaTeX packages as possible for the output, but I haven't indexed which ones would be necessary. I believe `amsmath` and `mathrsfs`should be enough.

2. I'm not sure how we should go about converting `sf` blocks.

3. I'm not sure how to implement binary and trinary operations, since the intended output is very sensitive to context.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
Also, I didn't quite understand the `:underover` business.

**Comment by GarkGarcia** [comment]
On regards to *2*, here's a list of all TeX macros currently used (I had to store it on a `.zip` file so that GitHub would accept it, but it's a JSON file).

[macros.zip](https://github.com/asciidoctor/asciimath/files/4535334/macros.zip)

**Comment by GarkGarcia** [comment]
I've confirmed that, as of now, all LaTeX commands and macros outputted by my (incomplete) implementation are covered by `amssymb` and `mathrsfs`. The only exception is `\twoheadrightarrowtail` (⤖), which I wasn't able to find a package for.

**Comment by pepijnve** [comment]
I've added some very rudimentary grammar and AST documentation at https://github.com/asciidoctor/asciimath/blob/master/AST.adoc
Nowhere near complete, but it's a start.

Regarding `subsup`, `underover`, etc. I suggest you have a look at the [MathML specification](https://www.w3.org/TR/MathML3/chapter3.html#presm.scrlim) on those. In short they're means of describing  subscript, superscript, underscript and overscript expressions. In the case of `{ :type => :ternary, :operator => :underover }` for instance, `s1`, `s2` and `s3` are the base, underscript and overscript expressions respectively. Maps pretty much 1-to-1 to MathML's `munderover` tag.

**Comment by GarkGarcia** [comment]
> I've confirmed that, as of now, all LaTeX commands and macros outputted by my (incomplete) implementation are covered by `amssymb` and `mathrsfs`. The only exception is `\twoheadrightarrowtail` (⤖), which I wasn't able to find a package for.

Also, `amsmath` is necessary for matrices.

**Comment by GarkGarcia** [comment]
> I've added some very rudimentary grammar and AST documentation at https://github.com/asciidoctor/asciimath/blob/master/AST.adoc
> Nowhere near complete, but it's a start.
Great!

> Regarding `subsup`, `underover`, etc. I suggest you have a look at the [MathML specification](https://www.w3.org/TR/MathML3/chapter3.html#presm.scrlim) on those. In short they're means of describing subscript, superscript, underscript and overscript expressions. In the case of `{ :type => :ternary, :operator => :underover }` for instance, `s1`, `s2` and `s3` are the base, underscript and overscript expressions respectively. Maps pretty much 1-to-1 to MathML's `munderover` tag.

I'll take a look at it, but I'm still unsure on how to deal with unary, binary and trinary operators. The problem is that the AST expresses multiple unary operators in terms of binary lowerlevel binary operatorion.

For example, `hat x` is expressed as `{:type=>:binary, :s1=>{:type=>:identifier, :c=>"x", :underover=>nil}, :s2=>{:type=>:operator, :c=>"^"}, :operator=>:over}`, which, in the current system, would get renderer as `\overset{ \^ }{ x }`. Besides being unidiomatic, this results are actually broken. The idiomatic way to express `hat x` in LaTeX is `\hat{x}`.

I think there are two ways we could go about this. We could either add a billion if-statments (covering each usecase mentioned in [asciimath.org](http://asciimath.org/#syntax)) or modify the AST (which may force us to add a billion if-statments on the other builders).

**Comment by pepijnve** [comment]
The current 'AST', if you can call it that, is kind of what asciimath.js uses internally and was defined in function of the MathML output. Through MathML glasses it makes sense: you have an expression with two parts (binary), the operator to combine the two is `over`, the first part is an identifier (`<mi>`) with value `x`. The second part is an operator (`<mo>`) with value `^`.
It's not surprising that it doesn't make sense in a LaTeX context.

You're right that if we make the AST more convenient for LaTeX it's going to end up being more cumbersome for MathML. Not sure what the best way forward is.

I'm open to suggestions here. If you have a proposal that would be acceptable for all three output generators I'm happy to change the AST.

**Comment by GarkGarcia** [comment]
> The current 'AST', if you can call it that, is kind of what asciimath.js uses internally and was defined in function of the MathML output. Through MathML glasses it makes sense: you have an expression with two parts (binary), the operator to combine the two is `over`, the first part is an identifier (`<mi>`) with value `x`. The second part is an operator (`<mo>`) with value `^`.
> It's not surprising that it doesn't make sense in a LaTeX context.
> 
> You're right that if we make the AST more convenient for LaTeX it's going to end up being more cumbersome for MathML. Not sure what the best way forward is.
> 
> I'm open to suggestions here. If you have a proposal that would be acceptable for all three output generators I'm happy to change the AST.

To be honest the current AST works fine for most things. The only major pain point is how operator (`:unary`, `:binary` and `:trinary`). The biggest issue is the fact that the order of operands is inconsistent (because it mimics the order of operands in MathML) and that some operators are expressed in terms of `:under` and `:over`.

My proposal is the following: why don't we bring the AST closer to actual asciimath syntax? That way each `Builder` class could traverse the tree and render it as intended without having to deal with the types of inconveniences we're facing in here. In precise terms:

1. Symbols should be identified by tokens (such as `:aleph`) instead of characters (such as `ℵ`). That way each builder can store an internal table that maps this tokens to their intended representation (like what I did with `LatexBuilde::CONSTANTS`). 

2. "Operators" (`:operator`) and "identifiers" (`:identifier`) should no be distinguished. Their syntax is the same. I undertand that this distinction is pretty relevant for the MathML and HTML builders, but those could be dealt with by storing an internal reference tables (an array or a set that stores all symbol identifiers that should be dealt with as operators).

3. "Operations" (`:unary`, `:binary`, `:trinary`) should be unified and expressed as `Hash`'s that store an array of operands. Each builder would then be responsible for segregating them appropriately. The order of the operands should be the same as the order in which they are expressing in asciimath.

4. Operations listed in [asciimath.org](https://asciimath.org/#syntax) (such as `hat` or `vec`) should no be expressed in terms of lower-level operations (such as`:over` or `:under`). Each builder would be responsible for converting the more specific representation to the more general one (the one done in terms of lower-level primitives) as necessary.

I understand those are not trivial changes, but I believe they would make the AST more flexible, allowing for easier extensibility. As such, I'd be glad to help on this transition. We could include it in this PR.

**Comment by GarkGarcia** [comment]
To be honest, I think the better approach would be to finish implementing LaTeX support with the current AST and then consider redesigning the AST in a different PR.

We should be almost done in here, there are few lose ends highlighted in the comments (the `# TODO: ...` ones).

**Comment by pepijnve** [comment]
> To be honest, I think the better approach would be to finish implementing LaTeX support with the current AST and then consider redesigning the AST in a different PR.

Agreed. Let's try to keep this PR focused on an initial LaTeX builder implementation.

**Comment by GarkGarcia** [comment]
We're almost done. I've tested the implementation as much as could with the examples provided in [asciimath.org](https://asciimath.org/#syntax). Could you provide me some more examples for testing.

**Comment by GarkGarcia** [comment]
There are two issues missing a fix:

1. How are we going to transpile the expression `sf "some text"`? The packages currently in use `asmmath`, `asmsymb` and `mathrsfs` do not provide a _sans-serif_ font. Also, as of now, I wasn't able to find a package that does so.

2. How are we going to transpile the expression `>->>`? As of now, I couldn't find a package that exposes this symbol.

I'd like your input on this issues. Also, be aware that we shouldn't rely too much on unconventional TeX packages.

**Comment by GarkGarcia** [comment]
By taking a look at [`asciimath2tex`](https://github.com/christianp/asciimath2tex/blob/0adfd3841fa7e68767ba781d44f07f8c9b296891/asciimath2tex.js#L311) source code, I was able to find a solution for the second issue (`\mathsf`).

**Comment by GarkGarcia** [comment]
The second can be solved by using the `stix` package. By using `stix` we can also avoid using `mathrsfs`.

**Comment by pepijnve** [comment]
No strong feelings either way. I haven't used LaTeX myself in years, so I don't think I'm well placed to make the judgement call regarding which packages are acceptable or not.

**Comment by GarkGarcia** [comment]
It's definitively ok to use the AMS packages (like I said before, they're pretty much standard). The only one which we should reconsider is `stix`. It would be better we could find a package that supports the `\mathscr` and `\twoheadrightarrowtail` macros which is already used by `asciidoctor-latex` and `asciidoctor-mathematical`.

Apparently this are all packages used by `asciidoctor-latex` (collect from a sample document I compiled to LaTeX):

* `geometry`
* `parskip`
* `tcolorbox`
* `lipsum`
* `epstopdf`
* `color`
* `amssymb`
* `amsthm`
* `mhchem`
* `fontspec`
* `ucharclasses`
* `hyperref`
* `graphicx`
* `wrapfig`

I couldn't found any official documentation about which packages are supported. I was also unable to find documentation about the packages supported by `mathematical` (which is used internally by `asciidoctor-mathematical`).

I'll continue to investigate this. I'll also see if any of the packages listed in here supports both macros.

**Comment by GarkGarcia** [comment]
Besides this, I think we're all done. Aren't we?

**Comment by GarkGarcia** [comment]
I've tested the implementation with the examples provided in https://asciimath.org, but I think we should test it some more. Could you assist me with this?

**Comment by pepijnve** [comment]
> Could you assist me with this?

Sorry, I don't have much time available for this at the moment. Paid work deadlines in combination with covid-19 lockdown measures doesn't leave much room for open source development.

One simple thing we could already do is add the LaTeX backend to `spec/parser_spec.rb`. For now this mainly consists of (asciimath input, expected output) pairs.

Longer term I think we should split this into two parts as well where we test asciimath -> AST and AST -> output separately.
Additionally, I've been wanting port over as many unit tests as possible from https://github.com/asciimath/asciimathml/blob/master/test/unittests.js. Those are all expressed in terms of MathML as well though, so I'm not sure how useful this will still be if we split the tests.

**Comment by GarkGarcia** [comment]
> Sorry, I don't have much time available for this at the moment. Paid work deadlines in combination with covid-19 lockdown measures doesn't leave much room for open source development.

No problem. Those are difficult times indeed. You've already helped by providing the test cases in `spec/parser_spec.rb`.

I've manually translated all test cases in `TEST_CASES` to LaTeX. I don't have much experience with `bundle` or `rake`. How could I run the tests?

**Comment by pepijnve** [comment]
I usually run the test directly from RubyMine. CLI workflow is to run `bundle install` once to get all your dependencies installed. Then run `bundle exec rake test` to execute the tests. The bundler part isn't strictly necessary (i.e., `rake test` may work just as well), but it ensures you're using the exact same versions of dependencies as Travis for instance.

**Comment by GarkGarcia** [comment]
Alright, we've passed all tests. 

In regards to `\mathscr` and `\twoheadrightarrowtail` (the commands that are not supported by `amsmath` and `amssymb`):

1. [Mathematical](https://github.com/gjtorikian/mathematical) supports `\mathscr`, but it doesn't support `\twoheadrightarrowtail`.

2. `asciidoctor-latex` does no support any of them.

In my opinion, we shouldn't worry too much about ``\twoheadrightarrowtail` (⤖). It's such an obscure symbol that it isn't supported by the AMS packages. we should replace it with `\twoheadrightarrow` (↠).

In regards to `\mathscr`, we could open a PR in `asciidoctor-latex` for them to include the `mathrsfs` package. There's no other way to provide support for the _script_ font.

**Comment by pepijnve** [comment]
One possibility is to raise an exception or log a warning and replace those two problematic bits with some approximation. I'm going to integrate this PR already; v1 doesn't have to be perfect. We can refine things in separate PRs.

**Comment by GarkGarcia** [comment]
Great! I've already opened PRs in `asciidoctor-latex` and `asciidoctor-mathematical` to notify their respective devs.

**Comment by pepijnve** [comment]
FYI I started working on the parser changes we discussed earlier. I'm going to try and get the parser done, fix up the MathML output and then push that work out on a feature branch already.

**Comment by GarkGarcia** [comment]
Great! I'll create an issue for further discussions.

**Pull request merged**
