### PR TITLE
Implemented LaTeX support for the 'color' binary operator

### PR DESCRIPTION
**Pull request by GarkGarcia**
Followup to #22 . Also corrected the rendering of '\ ', 'quad' and 'qquad'.

### CODE REVIEW

**Comment by GarkGarcia** [comment]
I'm finished with the commit.

**Comment by GarkGarcia** [comment]
@pepijnve I'll have to wait for you to merge the PR for me to submit other changes, since I accidentally used the master branch for this PR.

**Comment by GarkGarcia** [comment]
Btw @pepijnve. Would you mind making me a project maintainer? I'm not interested in permissions for merging PRs, I'd just like to be able to add labels to issues.

**Comment by pepijnve** [comment]
> Btw @pepijnve. Would you mind making me a project maintainer? I'm not interested in permissions for merging PRs, I'd just like to be able to add labels to some issues.

I was about to propose just that. Since I don't use the LaTeX code myself I don't think it's efficient to have everything pass through me.

**Comment by GarkGarcia** [comment]
> I was about to propose just that. Since I don't use the LaTeX code myself I don't think it's efficient to have everything pass through me.

Great!

Hey, it looks like bundle is having some problems in Travis CI:

* https://travis-ci.org/github/asciidoctor/asciimath/jobs/683019800

Could you take a look? It looks like it's a configuration issue.

**Comment by GarkGarcia** [comment]
Anyway, I'll merge the PR anyway, because it's passing all specs locally.

**Pull request merged**
