### PR TITLE
Fixed Zero Width Joiner character code

### PR DESCRIPTION
**Pull request by Tobski**
No idea how I didn't notice this in the past - can only assume I introduced this by accident _after_ testing.

### CODE REVIEW

**Comment by pepijnve** [comment]
Could you fix the tests to account for this change as well?

**Comment by Tobski** [comment]
> Could you fix the tests to account for this change as well?

Sorry that took so long - but yes, done now.

**Comment by Tobski** [comment]
Looks like everything passed except the jruby 1.7.27 CI build - I'm guessing that is an unrelated error though...?

**Comment by pepijnve** [comment]
```
0.19s$ gem install bundler -v '< 2'
243Error occurred during initialization of boot layer
244java.lang.module.FindException: Unable to derive module descriptor for /home/travis/.rvm/rubies/jruby-1.7.27/lib/jruby.jar
245Caused by: java.lang.module.InvalidModuleDescriptorException: YechtService.class found in top-level directory (unnamed package not allowed in module)
246The command "gem install bundler -v '< 2'" failed and exited with 1 during .
```

Looks like a java module system problem somewhere. Not related to this change indeed.

**Pull request merged**
