### PR TITLE
Fix the spacing of some standard AsciiMath operators

### PR DESCRIPTION
**Pull request by GarkGarcia**
A follow up to #37.

### CODE REVIEW

**Comment by davidfarmer** [comment]
I don't understand why there are capitalized versions of the trig functions.
Are those actually used anywhere?

Also, I think that `\text{ and }` , where there are spaces around the word,
is better.  That is not an operator, it is just text.  But in math it does need
the hard spaces, which (I am pretty sure) have to go inside the `\text{}`.
Similar for if, or, and maybe some other words.

**Comment by davidfarmer** [comment]
Also, for the lower case versions, use the built-in function:  `\csc` .

**Comment by GarkGarcia** [comment]
> Also, for the lower case versions, use the built-in function: `\csc` .

Sure. I'll create another PR for it. I merged this a bit too soon.

**Comment by GarkGarcia** [comment]
> I don't understand why there are capitalized versions of the trig functions. Are those actually used anywhere?

I'm not sure where those come from, but they are mentioned in the [symbols table](https://github.com/asciidoctor/asciimath/blob/master/AST.adoc#symbol-table). I guess they might be used in statistics or something.

> Also, I think that \text{ and } , where there are spaces around the word, is better. That is not an operator, it is just text. But in math it does need the hard spaces, which (I am pretty sure) have to go inside the \text{}. Similar for if, or, and maybe some other words.

I'm not too sure about this one. I'd consider _and_ and _or_ to be operators, even when written in text form.

**Comment by davidfarmer** [comment]
I guess I don't know what is meant by "and" and "or" in this context.

Is "or" being used as a conjunction or as an operator?

If you look at $x=5 \text{or} x=10$ you will see that it looks wrong;
you need the spaces around the or.  \operatorname does put in some space,
but (to my eye) not enough.

So maybe this is another instance of needing a way to determine what
type of object it is.

I googled to find out that apparently some misguided people do
ascribe a meaning to Sin with a capital S.  If the people who
officially define asciimath want to support that, well then what
can I say.

**Comment by GarkGarcia** [comment]
> I guess I don't know what is meant by "and" and "or" in this context.
>
> Is "or" being used as a conjunction or as an operator?

I _think_ `and`and `or` are meat to be textual equivalents of `wedge` and `vee` respectively. So I believe their meant for something like the following:

```
{x in X\ : \ P(x) and Q(x)}
```

**Comment by GarkGarcia** [comment]
>  \operatorname does put in some space, but (to my eye) not enough.

I see. We could transpile `and` to `\text{ and }` as you've proposed. I just don't like the idea of relying on spaces for this kind of thing. I'd prefer a more adaptable alternative, such as `\operatorname` (which only inserts spacing when there are adjacent symbols).

**Comment by davidfarmer** [comment]
operatorname seems like a fine compromise for now.

**Comment by pepijnve** [comment]
> I don't understand why there are capitalized versions of the trig functions.
Are those actually used anywhere?

@davidfarmer beats me to be honest. Those where inherited from http://asciimath.org/

In the issue on symbol table anomalies I pointed you to the symbol tables in this gem. In the original implementation the equivalent table exists at https://github.com/asciimath/asciimathml/blob/master/ASCIIMathML.js#L218
That’s essentially the join on the Ruby symbols of the two separate tables in this gem. We split the table here to get a cleaner separation of parser frontend and output backend. Without the split you end up trying to make LaTeX look like MathML or vice versa.

As you’ll see those capitalized trig functions are in the original implementation. I can’t really comment on the rationale behind them.

**Pull request merged**
