### PR TITLE
mfenced

### PR DESCRIPTION
**Pull request by opoudjis**
The current code does not use the `mfenced` MathML operator when rendering bracketed expressions. However, as shown in https://github.com/metanorma/metanorma-nist/issues/26, if the output MathML is converted in turn to OOXML, any brackets are not being recognised as such by Microsoft Word, and are not being resized automatically, unless the formula is edited manually.

This PR changes all instances of recognised lparen, rparen to `mfenced` operators, instead of `mo` operators; it deals with cases where only one bracket is used (which under Asciimath is balanced with `:}`.) This PR does not use the separators attribute of `mfenced`, and leaves it blank.

### CODE REVIEW

**Comment by pepijnve** [comment]
@opoudjis I'm happy to change this, but we'll be diverging a little bit from the output generated by the js implementation. Not sure if that's an issue or not.

**Comment by opoudjis** [comment]
This is quite a disruptive change, and I understand you need to make a strategic call across the board. All I can say it, our project needs it for correct Word OOXML.

**Comment by opoudjis** [comment]
I'm afraid I haven't tested the JS implementation, so I don't know. Happy for you to take your time to fix the JS, and in fact happy for us to discuss further whether mfenced should be applied as generally as I have done. We can use our fork in the short term.

**Comment by pepijnve** [comment]
Could you give https://github.com/asciidoctor/asciimath/commit/5793d32e9c0c0d3babc58612c4c0667d7b45b50b a try? With that change the referenced example gets processed correctly. No `mfenced` elements, but the parser correctly handles the matrix now.

**Comment by opoudjis** [comment]
I've run Word document generation with your recent change; the MathML I'm generating from the Asciimath is the same as your spec, modulo some escaping of characters:

Your MathML:

````
<math><mi>s</mi><msub><mi>\'</mi><mi>i</mi></msub><mo>=</mo><mrow><mo>{</mo><mtable><mtr><mtd><mrow><mo>&#x2212;</mo><mn>1</mn></mrow></mtd><mtd><mrow><mo>if</mo><msub><mi>s</mi><mi>i</mi></msub><mo>&gt;</mo><msub><mi>s</mi><mrow><mi>i</mi><mo>+</mo><mn>1</mn></mrow></msub></mrow></mtd></mtr><mtr><mtd><mrow><mo>+</mo><mn>1</mn></mrow></mtd><mtd><mrow><mo>if</mo><msub><mi>s</mi><mi>i</mi></msub><mo>&#x2264;</mo><msub><mi>s</mi><mrow><mi>i</mi><mo>+</mo><mn>1</mn></mrow></msub></mrow></mtd></mtr></mtable></mrow></math>'
````

My MathML, generated by running your latest fix:

````
<math xmlns="http://www.w3.org/1998/Math/MathML"><mi>s</mi><msub><mi>‘</mi><mi>i</mi></msub><mo>=</mo><mrow><mo>{</mo><mtable><mtr><mtd><mrow><mo>−</mo><mn>1</mn></mrow></mtd><mtd><mrow><mo>if</mo><msub><mi>s</mi><mi>i</mi></msub><mo>&gt;</mo><msub><mi>s</mi><mrow><mi>i</mi><mo>+</mo><mn>1</mn></mrow></msub></mrow></mtd></mtr><mtr><mtd><mrow><mo>+</mo><mn>1</mn></mrow></mtd><mtd><mrow><mo>if</mo><msub><mi>s</mi><mi>i</mi></msub><mo>≤</mo><msub><mi>s</mi><mrow><mi>i</mi><mo>+</mo><mn>1</mn></mrow></msub></mrow></mtd></mtr></mtable></mrow></math>
````

But of course, without mfenced, they still render poorly in Word. This is the OOXML conversion of that MathML:

````
<m:oMath>
  <m:r><m:t>s</m:t></m:r>
  <m:sSub><m:e><m:r><m:t>&#x2018;</m:t></m:r></m:e><m:sub><m:r><m:t>i</m:t></m:r></m:sub></m:sSub>
  <m:r><m:t>=</m:t></m:r>

    <m:r><m:t>{</m:t></m:r>
    <m:m><m:mPr><m:baseJc m:val="center"></m:baseJc><m:plcHide m:val="on"></m:plcHide><m:mcs><m:mc><m:mcPr><m:count m:val="2"></m:count><m:mcJc m:val=""></m:mcJc></m:mcPr></m:mc></m:mcs></m:mPr><m:mr><m:e>

            <m:r><m:t>&#x2212;1</m:t></m:r>


        </m:e><m:e>

            <m:r><m:t>if</m:t></m:r>
            <m:sSub><m:e><m:r><m:t>s</m:t></m:r></m:e><m:sub><m:r><m:t>i</m:t></m:r></m:sub></m:sSub>
            <m:r><m:t>&gt;</m:t></m:r>
            <m:sSub><m:e><m:r><m:t>s</m:t></m:r></m:e><m:sub>
                <m:r><m:t>i+1</m:t></m:r>


              </m:sub></m:sSub>

        </m:e></m:mr><m:mr><m:e>

            <m:r><m:t>+1</m:t></m:r>


        </m:e><m:e>

            <m:r><m:t>if</m:t></m:r>
            <m:sSub><m:e><m:r><m:t>s</m:t></m:r></m:e><m:sub><m:r><m:t>i</m:t></m:r></m:sub></m:sSub>
            <m:r><m:t>&#x2264;</m:t></m:r>
            <m:sSub><m:e><m:r><m:t>s</m:t></m:r></m:e><m:sub>
                <m:r><m:t>i+1</m:t></m:r>


              </m:sub></m:sSub>

        </m:e></m:mr></m:m>

</m:oMath>
````

and it renders as follows (with two other bracketed expressions):

Στιγμιότυπο 2019-10-25, 21 40 02

Let me try the pull request merging your fix in.

**Comment by pepijnve** [comment]
@opoudjis I did some further testing to see which implementation is 'right'. On asciimath.org inputting `s'_i = {(- 1, if s_i > s_(i + 1)),( + 1, if s_i <= s_(i + 1)):}` results in this:

Screenshot 2019-10-25 at 13 39 55

If I ask MathJax for the MathML code

Screenshot 2019-10-25 at 13 41 08

copy/paste it into an HTML file and open that in Safari I see:

Screenshot 2019-10-25 at 13 39 10

which is pretty much identical to the Word rendering.

So it looks like there's a difference in how MathJax renders/interprets MathML and how other tools do it.

I went back to the spec to figure out what should be happening. `mfenced` is essentially a short-hand for pairs of `mo`s. [It states](https://www.w3.org/TR/MathML2/chapter3.html#presm.mfenced) for instance
> For example, `<mfenced> <mi>x</mi> </mfenced>` renders as "(x)" and is equivalent to
> ```
> <mrow> <mo> ( </mo> <mi>x</mi> <mo> ) </mo> </mrow>
> ```
> and `<mfenced> <mi>x</mi> <mi>y</mi> </mfenced>` renders as "(x, y)" and is equivalent to
> ```
> <mrow>
>  <mo> ( </mo>
>  <mrow> <mi>x</mi> <mo>,</mo> <mi>y</mi> </mrow>
>  <mo> ) </mo>
> </mrow>
> ```

So there shouldn't actually be any difference between the two in terms of rendering. In other words, as far as I can tell based on the spec, `mfenced` does not imply stretching.

`mo` does have a `stretchy` attribute that should be set in order to get operator stretching. We could try setting that on the `mo` elements along with the `fence` attribute. If that works correctly for the OOXML conversion I would prefer that since it makes the intent explicit rather than relying on interpretation of what the expect default behaviour is for various elements.

**Comment by pepijnve** [comment]
@opoudjis based on https://www.w3.org/TR/MathML2/appendixf.html `{` should already be 'stretchy' by default. What code are you using for the MathML to OOXML conversion? Seems like the problem is there rather than in the MathML that's being generated.

**Comment by opoudjis** [comment]
We could rely on the W3C spec, or we would rely on what actually works in Word.

The converter I'm releasing is the prerelease MathML to OOXML stylesheet distributed by TEI, because they cannot redistribute the production stylesheet. However, the production stylesheet exhibits the same behaviour, as you can see if you copy paste the `<mo>` MathML straight into Word.

I've copy-pasted the expression with `<mo stretchy="true">{</mo>` into Word. Again, the stretchiness of the bracket is ignored. In fact, the production converter in Word does recognise the stretchy attribute, but only in mover/munder.

To expect Microsoft to abide by standards is somewhat... optimistic. Could we compromise by having the use of mfenced instead of mo be an option? As an optional argument to parse? I know it's dirty, but good Microsoft output is a real use case...

**Comment by pepijnve** [comment]
@opoudjis don't get me wrong, I'm not objecting against using `mfenced` instead of `mo`. Just trying to understand why one works and the other doesn't while they should effectively be identical.

I thought it might be preferable to be as explicit as possible in the generated MathML about what the desired rendering is (i.e., add an explicit `stretchy="true"` attribute), but if that doesn't have any effect then it doesn't really matter.

Lets revert back to the implicit stretchiness then and use `mfenced`.

**Comment by opoudjis** [comment]
And I know it's awful to have to fix output because Microsoft have done a poor job of implementing standards; that's why I'm happy for this to be a parse option, rather than required behaviour.

**Comment by pepijnve** [comment]
I went for a slight more minimalist change in 50a9a83442f6817212d64e0ebed2612033382d53, end result should be the same. Could you try that out?

**Comment by opoudjis** [comment]
A-OK!

Screen Shot 2019-10-26 at 20 44 32

**Comment by pepijnve** [comment]
Excellent! I’ll cut a new release that includes this change then.

**Comment by pepijnve** [comment]
Thanks for reporting the issue and the suggested fix btw. This exposed a pretty serious bug in the matrix handling logic of the parser that got fixed as well!

**Comment by opoudjis** [comment]
Pleasure working with you, Pepijn!

**Pull request closed without merging**
